# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'Firebase/Core'
pod 'Firebase/Messaging'

target 'standup_native_webview' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for standup_native_webview

  #target 'standup_native_webview-tvOSTests' do
    #inherit! :search_paths
    # Pods for testing
  #end

  target 'standup_native_webviewTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

#target 'standup_native_webview-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for standup_native_webview-tvOS

  #target 'standup_native_webview-tvOSTests' do
   # inherit! :search_paths
    # Pods for testing
  #end

#end
